import {Component,inject,signal,OnInit} from '@angular/core';import {FormsModule} from '@angular/forms';import {Router,RouterLink,ActivatedRoute} from '@angular/router';import {ArchiveApi} from '../../../../core/services/archive-api.service';import {AuthService} from '../../../../core/services/auth.service';import {DialogService} from '../../../../core/services/dialog.service';import {Catalogs} from '../../../../core/models/archive.model';import {LocationPickerComponent} from '../../../../shared/components/location-picker.component';
@Component({selector:'app-expediente-form',imports:[FormsModule,RouterLink,LocationPickerComponent],template:`
<div class="page-heading"><div><h1>{{id?'Editar':'Recibir'}} <strong>{{id?'expediente':'y catalogar'}}</strong></h1><p>Registra la existencia física antes de asignar ubicación y generar su etiqueta.</p></div><a routerLink="/buscar" class="btn secondary">Volver a Explorar</a></div>
<div class="workspace grid lg:grid-cols-[240px_1fr] gap-8">
<aside><p class="eyebrow mb-6">RUTA DEL REGISTRO</p><div class="space-y-7 text-[var(--deep)]"><div><strong>01 Prevalidar ingreso</strong><p class="mt-2 text-xs text-[var(--muted)]">Buscar posibles duplicados</p></div><div><strong>02 Clasificar expediente</strong><p class="mt-2 text-xs text-[var(--muted)]">Área, tipo y asunto</p></div><div><strong>03 Asignar ubicación</strong><p class="mt-2 text-xs text-[var(--muted)]">Archivo, estante, nivel y caja</p></div></div><div class="rule"></div><p class="text-xs leading-6 text-[var(--muted)]">Comprueba el número de trámite y año antes de continuar. El código único se genera al registrar.</p>@if(!id){<button class="text-button mt-5" (click)="restore()">Recuperar borrador local</button>}@if(auth.hasRole('ADMIN')){<a class="text-button mt-5 block" routerLink="/catalogos">Configurar áreas y ubicación →</a>}</aside>
<form #form="ngForm" class="panel" (ngSubmit)="submit()"><div class="section-title"><div><p class="eyebrow">NUEVO EXPEDIENTE FÍSICO</p><h2>Ficha de recepción</h2></div><span class="badge neutral">{{id?'Edición':'Código al registrar'}}</span></div>
<p class="eyebrow mb-4">01 PREVALIDACIÓN</p><div class="grid sm:grid-cols-[110px_1fr_auto] gap-4 items-end"><label>Año de ingreso<input type="number" name="anioIngreso" required min="1900" max="2200" [(ngModel)]="data.anioIngreso" (ngModelChange)="checked.set('')"></label><label>Número de trámite<input name="numeroTramite" required maxlength="50" [(ngModel)]="data.numeroTramite" (ngModelChange)="checked.set('')"></label>@if(!id){<button type="button" class="btn secondary" [disabled]="!data.numeroTramite||checking()" (click)="check()">Comprobar coincidencias</button>}</div>
@if(checked()){<p class="badge mt-4">✓ Sin coincidencias para este trámite y año</p>}
<div class="rule"></div><p class="eyebrow mb-5">02 CLASIFICACIÓN</p><div class="field-grid"><label>Número de documento<input name="numeroDocumento" required maxlength="50" [(ngModel)]="data.numeroDocumento"></label><label>Remitente<input name="remitente" required maxlength="255" [(ngModel)]="data.remitente"></label><label>Área de destino<select name="areaDestinoId" required [(ngModel)]="data.areaDestinoId"><option value="">Seleccionar área</option>@for(a of catalogs()?.areas;track a.id){<option [value]="a.id">{{a.nombre}}</option>}</select></label><label>Fecha del documento<input type="date" name="fechaDocumento" required [(ngModel)]="data.fechaDocumento"></label><label>Tipo documental<select name="tipoId" required [(ngModel)]="data.tipoId"><option value="">Seleccionar tipo</option>@for(t of catalogs()?.tipos;track t.id){<option [value]="t.id">{{t.nombre}}</option>}</select></label><label>Asunto<input name="asunto" required maxlength="500" [(ngModel)]="data.asunto"></label></div><label class="mt-5">Glosa · resumen del contenido<textarea name="glosa" rows="4" [(ngModel)]="data.glosa"></textarea></label>
<div class="rule"></div><p class="eyebrow mb-5">03 UBICACIÓN FÍSICA</p><app-location-picker [catalogs]="catalogs()" [(cajaId)]="data.cajaId"/><label class="max-w-40 mt-5">Número de folios<input name="numeroFolios" type="number" min="1" required [(ngModel)]="data.numeroFolios"></label>
<div class="rule"></div><div class="flex flex-wrap justify-end gap-3">@if(!id){<button type="button" class="btn secondary" (click)="draft()">Guardar borrador</button>}<button class="btn" [disabled]="!form.valid||!data.cajaId||(!id&&!checked())||busy()">{{busy()?'Guardando…':id?'Guardar cambios':'Registrar y generar QR'}}</button></div></form></div>`})
export class ExpedienteFormComponent implements OnInit {
api=inject(ArchiveApi);auth=inject(AuthService);dialog=inject(DialogService);router=inject(Router);route=inject(ActivatedRoute);catalogs=signal<Catalogs|null>(null);id=this.route.snapshot.paramMap.get('id');busy=signal(false);checking=signal(false);checked=signal('');
data={numeroTramite:'',anioIngreso:new Date().getFullYear(),numeroDocumento:'',remitente:'',areaDestinoId:'',tipoId:'',fechaDocumento:new Date().toLocaleDateString('en-CA'),asunto:'',glosa:'',cajaId:'',numeroFolios:1};
ngOnInit(){this.api.catalogs().subscribe({next:c=>this.catalogs.set(c),error:e=>this.dialog.error(e)});if(this.id)this.api.record(this.id).subscribe({next:r=>this.data={...this.data,...r,fechaDocumento:r.fechaDocumento.slice(0,10)},error:e=>this.dialog.error(e)});}
check(){this.checking.set(true);const key=this.data.numeroTramite+'|'+this.data.anioIngreso;this.api.duplicates(this.data.numeroTramite,this.data.anioIngreso).subscribe({next:r=>{this.checking.set(false);if(key!==this.data.numeroTramite+'|'+this.data.anioIngreso)return;this.checked.set(r.existe?'':key);this.dialog.info(r.existe?'Expediente existente':'Sin coincidencias',r.existe?'Ya hay un expediente con ese trámite y año. Revisa el archivo antes de registrarlo.':'Puedes continuar con la clasificación.');},error:e=>{this.checking.set(false);this.dialog.error(e);}});}
async submit(){if(this.busy())return;this.busy.set(true);if(!await this.dialog.ask(this.id?'Guardar cambios':'Registrar expediente','Confirma que los datos y la ubicación física son correctos.')){this.busy.set(false);return;}const request=this.id?this.api.edit(this.id,this.data):this.api.receive(this.data);request.subscribe({next:r=>{this.busy.set(false);if(!this.id)localStorage.removeItem(this.key());void this.router.navigate(['/expedientes',this.id??(r as {id:string}).id]);},error:e=>{this.busy.set(false);this.dialog.error(e);}});}
key(){return 'archive-draft-'+this.auth.usuario()?.usuarioId;}draft(){localStorage.setItem(this.key(),JSON.stringify(this.data));this.dialog.info('Borrador guardado','El borrador queda en este navegador. Todavía no se ha registrado el expediente.');}restore(){try{const d=localStorage.getItem(this.key());if(d){this.data={...this.data,...JSON.parse(d)};this.checked.set('');}else this.dialog.info('Sin borrador','No hay un borrador guardado en este navegador.');}catch{this.dialog.info('Borrador no disponible','No fue posible recuperar el borrador.');}}
}

