import {Component,inject,signal,OnInit} from '@angular/core';import {FormsModule} from '@angular/forms';import {Router,RouterLink,ActivatedRoute} from '@angular/router';import {ArchiveApi} from '../../../../core/services/archive-api.service';import {DialogService} from '../../../../core/services/dialog.service';import {RecordFile,User,Page} from '../../../../core/models/archive.model';import {RecordPickerComponent} from '../../../../shared/components/record-picker.component';import {PagerComponent} from '../../../../shared/components/pager.component';
@Component({selector:'app-prestamo-form',imports:[FormsModule,RouterLink,RecordPickerComponent,PagerComponent],template:`
<div class="page-heading"><div><h1>Registrar un préstamo <strong>con trazabilidad</strong></h1><p>Asigna responsable, modalidad y fecha de devolución antes de entregar el expediente.</p></div></div><div class="workspace grid lg:grid-cols-[320px_1fr] gap-6"><aside class="panel self-start"><p class="eyebrow">EXPEDIENTE SELECCIONADO</p>@if(record();as r){<h2 class="mt-4">{{r.codigoUnico}}</h2><p class="mt-3 text-xs">{{r.asunto}}</p><dl class="data-list mt-5"><div><dt>Ubicación</dt><dd>{{r.ubicacion}}</dd></div><div><dt>Volumen</dt><dd>{{r.numeroFolios}} folios</dd></div><div><dt>Estado</dt><dd>{{r.prestado?'En préstamo':'Disponible'}}</dd></div></dl><button class="text-button mt-5" (click)="record.set(null)">Cambiar expediente</button>}@else{<div class="mt-5"><app-record-picker (chosen)="record.set($event)"/></div>}</aside>
<form #f="ngForm" class="panel" (ngSubmit)="submit()"><p class="eyebrow">01 DATOS DE LA SOLICITUD</p><h2 class="mt-2 mb-6">¿Quién tendrá el expediente?</h2><label>Solicitante registrado<select name="solicitanteId" required [(ngModel)]="solicitanteId"><option value="">Selecciona un usuario activo</option>@for(u of users()?.contenido;track u.id){@if(u.activo){<option [value]="u.id">{{u.nombre}} · {{u.correo}}</option>}}</select></label><app-pager [page]="users()?.pagina??0" [size]="10" [total]="users()?.totalElementos??0" (changed)="loadUsers($event)"/><p class="text-xs text-[var(--muted)]">Los solicitantes deben contar con una cuenta registrada.</p>
<div class="rule"></div><p class="eyebrow mb-5">02 MODALIDAD</p><div class="grid sm:grid-cols-2 gap-4"><button type="button" class="panel text-left" [class]="tipoSolicitud==='FISICO'?'!border-[var(--brand)] !bg-[#E8F2F7]':''" (click)="tipoSolicitud='FISICO'"><strong>Expediente físico</strong><p class="text-xs text-[var(--muted)] mt-3">Retiro y devolución obligatoria</p></button><button type="button" class="panel text-left" [class]="tipoSolicitud==='DIGITAL'?'!border-[var(--brand)] !bg-[#E8F2F7]':''" (click)="tipoSolicitud='DIGITAL'"><strong>Copia digital</strong><p class="text-xs text-[var(--muted)] mt-3">Solicitud registrada, sin retirar el original</p></button></div><label class="mt-6">Devolución prevista<input type="date" required [min]="today" name="fecha" [(ngModel)]="fechaDevolucionPrevista"></label><label class="mt-5">Motivo del préstamo<textarea name="motivo" rows="4" required [(ngModel)]="motivo"></textarea></label><label class="flex items-center gap-3 mt-6"><input type="checkbox" name="custodia" [(ngModel)]="aceptaCustodia">El solicitante acepta la custodia hasta registrar la devolución.</label><div class="flex justify-end gap-3 mt-8"><a class="btn secondary" routerLink="/prestamos">Cancelar</a><button class="btn" [disabled]="!f.valid||!record()||!aceptaCustodia||busy()||(tipoSolicitud==='FISICO'&&record()?.prestado)">Registrar préstamo</button></div></form></div>`})
export class PrestamoFormComponent implements OnInit {api=inject(ArchiveApi);dialog=inject(DialogService);router=inject(Router);route=inject(ActivatedRoute);record=signal<RecordFile|null>(null);users=signal<Page<User>|null>(null);busy=signal(false);solicitanteId='';tipoSolicitud='FISICO';fechaDevolucionPrevista='';motivo='';aceptaCustodia=false;today=new Date().toLocaleDateString('en-CA');
ngOnInit(){const id=this.route.snapshot.queryParamMap.get('expedienteId');if(id)this.api.record(id).subscribe({next:r=>this.record.set(r),error:e=>this.dialog.error(e)});this.loadUsers(0);}loadUsers(p:number){this.api.users(p).subscribe({next:r=>this.users.set(r),error:e=>this.dialog.error(e)});}
async submit(){if(this.busy())return;this.busy.set(true);if(!await this.dialog.ask('Registrar préstamo','Confirma la entrega y la fecha de devolución del expediente.')){this.busy.set(false);return;}this.api.lend({expedienteId:this.record()!.id,solicitanteId:this.solicitanteId,tipoSolicitud:this.tipoSolicitud,fechaDevolucionPrevista:this.fechaDevolucionPrevista,motivo:this.motivo,aceptaCustodia:this.aceptaCustodia}).subscribe({next:()=>{this.busy.set(false);void this.router.navigate(['/prestamos']);},error:e=>{this.busy.set(false);this.dialog.error(e);}});}
}

